version: '3.9'

services:
  langgraph-api:
    build: ./Agent
    env_file: .env 
    network_mode: "host"
    volumes:
      - langraph_data:/app/.langgraph_api 
    networks:
      - langgraph-net

  frontend:
    build:
      context: ./frontend
      args:
        - NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
        - NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}
    env_file: .env
    network_mode: "host"
    depends_on:
      - langgraph-api
    networks:
      - langgraph-net

volumes:
  langraph_data:

networks:
  langgraph-net: